baseurl = "https://example.com"
title = "Voce Clara"
languageCode = "de"
DefaultContentLanguage = "de"
paginate = "10" # Number of posts per page
theme = "hugo-dpsg"

[Author] # Used in authorbox
  name = "Scout Master"
  bio = "The Scout Master is the leader of this local scout group"
  avatar = "img/avatar.png"

[Params]
  description = "Welcome to our scout group!" # Site description. Used in meta description
  copyright = "DGSP local group" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  indexPager = true # Show pager navigation on index page
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "02.01.2006" # Change the format of dates
  customCSS = [
    "css/custom.css"
  ]

[Params.style.vars]
  highlightColor = "#003056" # Override main theme color

[Params.logo]
  image = "logo512.png" # Logo image. Path relative to "static"
  header = "melody.jpg" # Header image. Path relative to "static"
  title = "Voce Clara" # Logo title, otherwise will use site title
  subtitle = "Skola odhaleni hlasu" # Logo subtitle

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.footer]
  text = "Voce Clara" # Extra text in footer row, understands markdown

# Custom menu items, normally controlled via front matter in /content files
[menu]

  [[menu.main]]
    identifier = "start"
    name = "Start"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "people"
    name = "People"
    url = "/people/"
    weight = 3

  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events/"
    weight = 4

